apiVersion: v1
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: hello
  namespace: default
  labels:
    app: hello
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
        name: hello
    spec:
      containers:
      - image: valentinnc/hello:{{ .Values.tag }}
        name: hello
        env: 
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP


